safe: true
lsi: false
pygments: true

markdown: rdiscount

name: svperstarz.github.io
author: Moojin Jung
subtitle: svperstarz's blog
url: http://svperstarz.github.io

exclude: ['README*', LICENSE, 'Gemfile*', feed ]


