safe: true
lsi: false
highlighter: pygments

markdown: kramdown

name: svperstarz.github.io
author: Moojin Jung
subtitle: svperstarz's blog
url: http://svperstarz.github.io
permalink: /:year/:month/:title
relative_permalink: false

exclude: ['README*', LICENSE, 'Gemfile*', feed ]

