#! /usr/bin/env bash

E_BADARGS=65
E_BADFILE=66

[[ $# -eq 1 ]] || exit $E_BADARGS

text_ko="$1"
text_en="../docs/$1"

if [[ ! -f "$text_en" ]]
then
	echo "THERE IS NO SOURCE: $text_en"
	exit $E_BADFILE
fi

if [[ ! -r "$text_ko" || ! -w "$text_ko" ]]
then
	if [[ ! -e "$text_ko" ]]
	then
		echo "COPYING SOURCE: $text_en TO TARGET: $text_ko"
		cp $text_en $text_ko
	else
		echo "TARGET: $text_ko IS NOT READABLE OR WRITABLE"
		exit $E_BADFILE
	fi
fi

sleep 1

gvim +1 "$text_ko" \
	+"new +1 $text_en" \
	+"vnew +1 MEMO | set ts=16 | norm H40|w" \
	+"set ft=| set scb | set crb | norm j" \
	+"set ft=| set scb | set crb | norm \`\"" +"set et | set tw=80 | set noimd"

